pipeline {
    agent any

    environment {
        COMPOSE_FILE = 'UpdateHedgeDoc/files/docker-compose.yml'
        REGISTRY_API = 'https://quay.io/api/v1/repository/hedgedoc/hedgedoc/tag/'
    }

    stages {
        stage('Check New Image') {
            steps {
                script {
                    def currentTag = sh(script: "grep -oP 'quay.io/hedgedoc/hedgedoc:\\K[a-zA-Z0-9.-]+-alpine' ${COMPOSE_FILE}", returnStdout: true).trim()
                    echo "Current Tag in docker-compose: ${currentTag}"
                    def latestTagCmd = """
                        curl -s "${REGISTRY_API}?limit=100" | \
			grep -oP '"name": "\\K[a-zA-Z0-9.-]+-alpine(?=")' | head -n 1
                    """
                    def latestTag = sh(script: latestTagCmd, returnStdout: true).trim()
                    echo "Last tag available in Quay.io: ${latestTag}"
                    if (latestTag == "") {
                        error "Can't get last tag in Quay.io"
                    }
                    if (currentTag != latestTag) {
                        echo "New version Available! Updating from ${currentTag} to ${latestTag}."
                        env.NEW_TAG_FOUND = 'true'
                        env.LATEST_TAG = latestTag
                        env.CURRENT_TAG = currentTag
                    } else {
                        echo "Container in last version: ${currentTag}."
                        env.NEW_TAG_FOUND = 'false'
                    }
                }
            }
        }

        stage('Deploy Update') {
            when {
                environment name: 'NEW_TAG_FOUND', value: 'true'
            }
            steps {
                script {
                    def composePath = "${env.WORKSPACE}/${env.COMPOSE_DIR}/docker-compose.yml"
                    sh "sed -i 's/${env.CURRENT_TAG}/${env.LATEST_TAG}/g' '${composePath}'"
                    echo "Stopping current service..."
                    sh "docker compose -f '${composePath}' stop"
                    echo "Removing container..."
                    sh "docker compose -f '${composePath}' rm -f"
                    echo "Removing old image..."
                    sh "docker rmi quay.io/hedgedoc/hedgedoc:${env.CURRENT_TAG} || true"
                    echo "Deploying new version..."
                    sh "docker compose -f '${composePath}' up -d"
                }
            }
        } 
    }
}
